builds:
  - binary: kubectl-provision
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

brew:
  name: provision
  github:
    owner: ernoaapa
    name: homebrew-kubectl-plugins
  homepage: "https://github.com/ernoaapa/kubectl-provision"
  description: "Kubectl plugin to provision a node"
  test: |
    system "#{bin}/kubectl-provision --version"

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
